import React, { FC, ReactNode } from "react";
import scss from "./Layout.module.scss";
import Head from "next/head";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import ProvidersWrapper from "@/components/auth/ProvidersWrapper";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
	children: ReactNode;
}

const Layout: FC<LayoutProps> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ProvidersWrapper>
				<div className={`${inter.className} ${scss.layout}`}>
					<header>
						<Header />
					</header>
					{children}
					<footer>
						<Footer />
					</footer>
				</div>
			</ProvidersWrapper>
		</>
	);
};
export default Layout;
